Repository SIGS-UnB/core, pull requests merged in 2018-11, with the labels that each got.

#115 [CLEAN CODE] Applies clean code to seeds.rb
  SIGS/db/schema.rb
  SIGS/db/seeds.rb
  SIGS/db/seeds/001_create_campi.rb
  SIGS/db/seeds/002_create_departments.rb
  SIGS/db/seeds/003_create_courses.rb
  SIGS/db/seeds/004_create_coordinator_users.rb
  SIGS/db/seeds/005_create_deg_users.rb
  SIGS/db/seeds/006_create_administrative_assistant_users.rb
  SIGS/db/seeds/007_create_buildings.rb
  SIGS/db/seeds/008_create_categories.rb
  SIGS/db/seeds/009_0_create_rooms.rb
  SIGS/db/seeds/009_1_icc_at_rooms.rb
  SIGS/db/seeds/009_2_icc_bt_rooms.rb
  SIGS/db/seeds/009_3_icc_b1_rooms.rb
  SIGS/db/seeds/009_4_icc_anfiteatro_rooms.rb
  SIGS/db/seeds/009_5_bsas_rooms.rb
  SIGS/db/seeds/009_6_bsan_rooms.rb
  SIGS/db/seeds/009_7_pat_rooms.rb
  SIGS/db/seeds/009_8_pjc_rooms.rb
  SIGS/db/seeds/009_9_baes_rooms.rb
  SIGS/db/seeds/010_create_disciplines.rb
  SIGS/db/seeds/011_create_school_rooms.rb
  SIGS/db/seeds/012_create_periods.rb
  SIGS/db/seeds/013_create_allocations.rb
  SIGS/db/seeds/014_create_extension_allocations.rb
  SIGS/db/seeds/015_create_api_users.rb
Labels: clean code

#121 Code Duplicity
  .codeclimate.yml
  SIGS/app/controllers/allocations_controller.rb
  SIGS/app/controllers/solicitations_controller.rb
  SIGS/app/helpers/date_allocation_helper.rb
Labels: SMTC, clean code

#122 Refactor sidebar in modules
  SIGS/app/assets/javascripts/sidebar.js
  SIGS/app/views/layouts/_sidebar.html.erb
  SIGS/app/views/layouts/application.html.erb
  SIGS/app/views/sidebar/_sidebar.html.erb
  SIGS/app/views/sidebar/_sublist_permission_0.html.erb
  SIGS/app/views/sidebar/_sublist_permission_1.html.erb
  SIGS/app/views/sidebar/_sublist_permission_2.html.erb
  SIGS/app/views/sidebar/_sublist_permission_all.html.erb
  SIGS/app/views/sidebar/_sublist_permission_not_0.html.erb
  SIGS/config/initializers/assets.rb
  SIGS/db/schema.rb
Labels: clean, clean code, enhancement

#124 Refactor alert container
  SIGS/app/assets/javascripts/sidebar.js
  SIGS/app/assets/stylesheets/form.scss
  SIGS/app/assets/stylesheets/style.scss
  SIGS/app/views/allocations/new_education.html.erb
  SIGS/app/views/layouts/_alert.html.erb
  SIGS/app/views/layouts/application.html.erb
  SIGS/app/views/reports/school_reports.html.erb
Labels: clean, clean code, enhancement, front
