Repository SIGS-UnB/core, pull requests merged in 2018-10, with the labels that each got.

#50 #49 CC Test Reporter
  .travis.yml
  README.md
Labels: bug

#53 #52 SIGS Deploy
  .gitignore
  README.md
  script/deploy.sh
  script/production-deploy.sh
  script/staging-deploy.sh
Labels: bug, enhancement

#36 Refatoração da tela de Login
  SIGS/app/assets/images/background_unb.jpg
  SIGS/app/assets/images/unb-background-login.jpg
  SIGS/app/assets/images/unb_logo.png
  SIGS/app/assets/stylesheets/application.css.sass
  SIGS/app/assets/stylesheets/main.scss
  SIGS/app/assets/stylesheets/new.scss
  SIGS/app/assets/stylesheets/style.scss
  SIGS/app/views/layouts/application.html.erb
  SIGS/app/views/sessions/new.html.erb
  SIGS/coverage/.resultset.json
  SIGS/coverage/index.html
  SIGS/db/schema.rb
Labels: enhancement, front

#63 [HOTFIX] Enhance Deploy
  script/deploy.sh
Labels: bug, enhancement

#66 Update ruby version and image on readme
  README.md
Labels: documentation, enhancement

#71 [Hotfix] #70 sshpass error
  script/staging-deploy.sh
Labels: bug

#69 [Feature] #34 Profile Image
  .gitignore
  SIGS/.gitignore
  SIGS/Gemfile
  SIGS/Gemfile.lock
  SIGS/app/controllers/users_controller.rb
  SIGS/app/models/user.rb
  SIGS/app/uploaders/avatar_uploader.rb
  SIGS/app/views/layouts/_navbar.html.erb
  SIGS/app/views/users/edit.html.erb
  SIGS/app/views/users/new.html.erb
  SIGS/db/migrate/20181009005802_add_column_to_user.rb
  SIGS/db/schema.rb
Labels: enhancement, feature, front

#79 Fix Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#83 #82 Updating Readme
  README.md
Labels: bug, documentation

#87 Fix #84 - User Edit
  SIGS/app/views/users/edit.html.erb
Labels: bug, enhancement, feature, front

#101 [Feature] #72 Password Visibility
  SIGS/app/views/sessions/login.html.erb
Labels: Hacktoberfest, enhancement, feature, front

#51 Arrumando Homepage da aplicação
  SIGS/app/assets/images/anonimo.png
  SIGS/app/assets/images/avatar.png
  SIGS/app/assets/images/oferta.png
  SIGS/app/assets/images/relatorios.png
  SIGS/app/assets/images/salas.png
  SIGS/app/assets/images/solicitacoes.png
  SIGS/app/assets/javascripts/sidebar.js
  SIGS/app/assets/stylesheets/form.scss
  SIGS/app/assets/stylesheets/navbar.scss
  SIGS/app/assets/stylesheets/sidebar.scss
  SIGS/app/assets/stylesheets/style.scss
  SIGS/app/assets/stylesheets/user.scss
  SIGS/app/views/layouts/_navbar.html.erb
  SIGS/app/views/layouts/_sidebar.html.erb
  SIGS/app/views/layouts/application.html.erb
  SIGS/app/views/rooms/index.html.erb
  SIGS/app/views/users/show.html.erb
  SIGS/features/step_definitions/generate_discipline_allocation_reports_steps.rb
  SIGS/features/step_definitions/generate_room_allocation_reports_steps.rb
  SIGS/features/step_definitions/generate_school_room_reports_steps.rb
  SIGS/tmp/.keep
Labels: enhancement
