Repository SIGS-UnB/core, pull requests merged in 2018-09, with the labels that each got.

#23 Fix names and links register screen
  SIGS/app/views/users/new.html.erb
Labels: enhancement

#26 Separates navbar and footer from application layout
  SIGS/app/views/layouts/_footer.html.erb
  SIGS/app/views/layouts/_navbar.html.erb
  SIGS/app/views/layouts/application.html.erb
  SIGS/features/19_token_authenticate_api.feature
Labels: enhancement, front

#29 Refactor navbar
  SIGS/app/assets/images/avatar.png
  SIGS/app/assets/images/unb.png
  SIGS/app/assets/stylesheets/footer.scss
  SIGS/app/assets/stylesheets/navbar.scss
  SIGS/app/views/layouts/_navbar.html.erb
Labels: enhancement, front

#44 Makes code search field find with substrings
  SIGS/app/helpers/rooms_helper.rb
  SIGS/app/views/rooms/index.html.erb
Labels: bug, enhancement

#42 Adds production docker
  SIGS/config/database.yml
  SIGS/start-prod.sh
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker/dev/Dockerfile
  docker/prod/Dockerfile
  script/production-deploy.sh
  script/staging-deploy.sh
Labels: enhancement

#43 Vagrant and Puppet removal
  Vagrantfile
  config.inc.php
  puppet/manifests/default.pp
  puppet/modules/apache/manifests/init.pp
  puppet/modules/git/manifests/init.pp
  puppet/modules/mysql/manifests/init.pp
  puppet/modules/php/manifests/init.pp
  puppet/modules/postgresql/manifests/init.pp
  puppet/modules/rails/manifests/init.pp
  puppet/modules/system-update/manifests/init.pp
  script/script.sh
Labels: clean

#45 Adds room capacity to rooms list
  SIGS/app/views/rooms/index.html.erb
Labels: enhancement, feature, front
