Repository SIGS-UnB/core, pull requests merged in 2019-07, with the labels that each got.

#255 Applying solid principles by Adrianne and Maria Luiza
  app/controllers/allocations_controller.rb
  app/controllers/api_users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/coordinators_controller.rb
  app/controllers/degs_controller.rb
  app/controllers/extensions_controller.rb
  app/controllers/parsers_controller.rb
  app/controllers/periods_controller.rb
  app/controllers/prepare_solicitations_to_save.rb
  app/controllers/reports_controller.rb
  app/controllers/reports_disciplines_controller.rb
  app/controllers/reports_school_rooms_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/school_rooms_controller.rb
  app/controllers/solicitations_controller.rb
  app/controllers/table_room.rb
  app/helpers/allocation_extensions_helper.rb
  app/helpers/allocation_helper.rb
  app/helpers/filters_rooms_extensions_helper.rb
  app/helpers/filters_rooms_helper.rb
  app/helpers/reports_disciplines_helper.rb
  app/helpers/reports_helper.rb
  app/helpers/rooms_helper.rb
  app/views/allocations/new.html.erb
  app/views/rooms/index.html.erb
  app/views/users/show.html.erb
  db/seeds/009_0_create_rooms.rb
  features/07_filter_rooms.feature
  features/step_definitions/filter_rooms_steps.rb
  lib/modules/rooms_util.rb
  public/stylesheets/user.scss
  spec/controllers/rooms_controller_spec.rb
Labels: SOLID, clean, clean code, improvement

#259 Fix room filter by campus
  app/controllers/rooms_controller.rb
  app/helpers/filters_rooms_extensions_helper.rb
  app/views/rooms/index.html.erb
Labels: bug, debts

#261 Organize home layout
  app/views/users/show.html.erb
  public/images/adjustment.png
  public/images/grade.png
  public/images/period.png
  public/stylesheets/user.scss
Labels: improvement

#264 Show just coordinator's buildings in allocation
  app/controllers/allocations_controller.rb
  app/helpers/school_rooms_helper.rb
Labels: improvement

#251 Fix friendly id params
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/models/user.rb
  spec/controllers/users_controller_spec.rb
Labels: feature, improvement, usability

#266 Improving school room page layout
  app/views/school_rooms/index.html.erb
  public/stylesheets/school_rooms.scss
Labels: front, improvement, usability

#269 Show search school room in same page
  app/controllers/school_rooms_controller.rb
  app/helpers/school_rooms_helper.rb
  app/views/school_rooms/filtering_params.html.erb
  app/views/school_rooms/index.html.erb
  config/routes.rb
  features/08_search_school_room.feature
  features/step_definitions/search_school_room.rb
  spec/controllers/school_rooms_controller_spec.rb
Labels: improvement

#267 Applying clean code principles by Stefane
  app/helpers/school_rooms_helper.rb
  app/helpers/solicitations_helper.rb
Labels: clean, clean code

#277 Adding categories and info on room cards
  app/controllers/rooms_controller.rb
  app/helpers/rooms_helper.rb
  app/models/room.rb
  app/views/rooms/_show.html.erb
  app/views/rooms/edit.html.erb
  db/migrate/20190710050821_add_details_to_rooms.rb
  db/seeds/008_create_categories.rb
  db/seeds/009_0_create_rooms.rb
  db/seeds/009_1_icc_at_rooms.rb
  db/seeds/009_2_icc_bt_rooms.rb
  db/seeds/009_3_icc_b1_rooms.rb
  db/seeds/009_4_icc_anfiteatro_rooms.rb
  db/seeds/009_5_bsas_rooms.rb
  db/seeds/009_6_bsan_rooms.rb
  db/seeds/009_7_pat_rooms.rb
  db/seeds/009_8_pjc_rooms.rb
  db/seeds/009_9_baes_rooms.rb
  features/07_filter_rooms.feature
  features/step_definitions/filter_rooms_steps.rb
  spec/controllers/allocations_controller_spec.rb
  spec/controllers/report_controller_spec.rb
  spec/controllers/reports_disciplines_controller_spec.rb
  spec/controllers/reports_school_rooms_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
  spec/controllers/solicitations_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: back-end, front, improvement

#278 Improvement edit class page
  app/views/school_rooms/edit.html.erb
  app/views/school_rooms/new.html.erb
  app/views/solicitations/_solicitations.html.erb
  app/views/solicitations/index.erb
  app/views/solicitations/show.erb
Labels: front, improvement

#274 Show search school room in same page
  app/controllers/school_rooms_controller.rb
  app/helpers/school_rooms_helper.rb
  app/views/school_rooms/filtering_params.html.erb
  app/views/school_rooms/index.html.erb
  config/routes.rb
  features/08_search_school_room.feature
  features/step_definitions/search_school_room.rb
  public/stylesheets/school_rooms.scss
  spec/controllers/school_rooms_controller_spec.rb
Labels: improvement
