Repository SIGS-UnB/core, pull requests merged in 2019-11, with the labels that each got.

#310 Improvement/288 course search in class association
  .rubocop_todo.yml
  app/controllers/school_rooms_controller.rb
  app/views/school_rooms/new.html.erb
Labels: GCES, front

#311 Improvement/283 discipline selection when creating or editing a class
  app/views/school_rooms/new.html.erb
  db/seeds/010_create_disciplines.rb
Labels: GCES, front

#315 Clean and Solid
  app/controllers/allocations_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/school_rooms_controller.rb
  app/controllers/solicitations_controller.rb
  app/controllers/users_controller.rb
  app/helpers/coordinator_helper.rb
  app/helpers/courses_helper.rb
  app/helpers/school_rooms_helper.rb
  app/helpers/sessions_helper.rb
  app/helpers/user_helper.rb
  app/validators/requester_validator.rb
  app/views/courses/courses_by_coordinator.html.erb
  app/views/courses/courses_by_user.html.erb
  app/views/school_rooms/edit.html.erb
  app/views/school_rooms/index.html.erb
  app/views/school_rooms/new.html.erb
  config/routes.rb
  lib/modules/user_module.rb
  spec/controllers/courses_controller_spec.rb
  spec/helpers/coordinator_helper_spec.rb
  spec/helpers/courses_helper_spec.rb
Labels: GCES, clean code

#324 Clean solid code caio
  app/controllers/school_rooms_controller.rb
  app/helpers/school_rooms_helper.rb
  spec/controllers/school_rooms_controller_spec.rb
Labels: GCES, SOLID, clean code

#322 Clean solid code joao
  app/controllers/administrative_assistants_controller.rb
  app/controllers/api_users_controller.rb
  app/helpers/administrative_assistant_helper.rb
Labels: GCES, clean code
