Repository SIGS-UnB/core, pull requests merged in 2019-04, with the labels that each got.

#177 [Bugfix] Fixing delete room functionality
  SIGS/app/controllers/rooms_controller.rb
  SIGS/app/views/rooms/index.html.erb
  SIGS/config/routes.rb
  SIGS/coverage/.resultset.json
  SIGS/coverage/index.html
  SIGS/spec/controllers/rooms_controller_spec.rb
Labels: bug, front

#183 [Improvement] Include Improvement as type of branch
  .github/CONTRIBUTING.md
Labels: documentation, good first issue, improvement

#180 [Improvement] Simplifying action buttons of school_rooms list
  SIGS/app/views/school_rooms/index.html.erb
Labels: clean, feature, front, improvement

#194 Show me the code 1 - 2019.1 Pre-release 2.1
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .gitignore
  README.md
  SIGS/app/assets/stylesheets/components/form.scss
  SIGS/app/assets/stylesheets/rooms.scss
  SIGS/app/assets/stylesheets/rooms_filter.scss
  SIGS/app/controllers/rooms_controller.rb
  SIGS/app/controllers/solicitations_controller.rb
  SIGS/app/views/rooms/_rooms_filter.html.erb
  SIGS/app/views/rooms/index.html.erb
  SIGS/app/views/school_rooms/index.html.erb
  SIGS/app/views/solicitations/_solicitations.html.erb
  SIGS/app/views/solicitations/index.erb
  SIGS/app/views/users/edit.html.erb
  SIGS/config/routes.rb
  SIGS/coverage/.resultset.json
  SIGS/coverage/index.html
  SIGS/spec/controllers/rooms_controller_spec.rb
  docker-compose-dev.yml
  docker-compose-homolog.yml
  docker-compose-prod.yml
  docs/GPG_KEYS.md
  keys.gpg
Labels: Pre-release, SMTC
